# Generated by Django 2.2.11 on 2020-04-04 06:44

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('details', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
            ],
        ),
    ]
